version: '3.9'
services:
  nodejs:
    image: node:lts
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local